In [ ]:
# input
pred_sites_file = "../../data/pred_site_plddt_proba.tsv"
afdb_anno = "../../../collect_annotation/afdb_anno/data/entryId-repId-pfamId-tedId-annoLevel-sp.tsv"

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_table(pred_sites_file, usecols=["seq_id", 'proba'])
site_probas = df['proba'].map(lambda x: np.median([float(i) for i in x.split(",")])).tolist()

In [8]:
cnts, edges = np.histogram(site_probas, bins=[0.2, 0.4, 0.6, 0.8, 1.0])
len(site_probas)
cnts / len(site_probas)
edges

46143213

array([0.07437228, 0.08940368, 0.17387313, 0.66235091])

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
df_anno = pd.read_table(afdb_anno, header=None, names=['seq_id', '_', "__", "___", 'anno_level', 'sp'], usecols=['seq_id', 'anno_level']) 
site_anno_ids = set(df_anno[df_anno['anno_level'].map(lambda x: ('3' in str(x) or '4' in str(x)) if pd.notna(x) else False)]['seq_id'])
del df_anno
anno_site_probas = [p for sid, p in zip(df['seq_id'], site_probas) if sid in site_anno_ids]

In [9]:
cnts, edges = np.histogram(anno_site_probas, bins=[0.2, 0.4, 0.6, 0.8, 1.0])
cnts / len(anno_site_probas)
edges

array([0.0434672 , 0.05852616, 0.16301864, 0.734988  ])

array([0.2, 0.4, 0.6, 0.8, 1. ])